# Generated by Django 3.1.6 on 2021-02-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('menuName', models.CharField(max_length=50, verbose_name='Menu Name')),
                ('menuPDF', models.FileField(upload_to='media/', verbose_name='Menu PDF')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
